export const skillsList: string[] = [
  "JavaScript",
  "GIT",
  "React",
  "TailwindCSS",
  "HTML",
  "Redux",
  "TypeScript",
  "Vercel",
  "SCRUM",
  "Recharts",
  "Agile Development",
  "CSS",
  "Component-Based Architecture",
  "Axios",
  "Responsive Web Design",
  "Jira",
  "Swift IOS",
];
