export const skillsList: string[] = [
  "JavaScript ES6+",
  "GIT",
  "React",
  "TailwindCSS",
  "TypeScript",
  "HTML5",
  "Redux",
  "Vercel",
  "SCRUM",
  "CSS3",
  "Agile Development",
  "Recharts",
  "Axios API",
  "CBA",
  "Responsive Web Design",
  "Jira",
  "Swift IOS",
  "UI/UX Best Practices"
];
